### ISSUE TITLE
Master TODO

### ISSUE THREAD

**Issue by YUR0ii** [YUR0ii/STPC#1]
- [x] Merge hit/hurtboxes
- [x] Add other box types (push, projectile, projectile vulnerable, throw, throwable (air/ground))
- [x] Refactor animation to merge attacks and normal (faf > actionable frames)
- [x] Move from absolute position to relative grid
- [x] Base collision on pushboxes
- [x] Create format for storage of animation data
- [x] ^ Link to character creation helper
